version: '3.7'

services:

  postgres:
    image: postgres:11.5-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
  postgres-data:

